### ISSUE TITLE
能不能添加一个开关，全部都同步，我只想这个专门写博客的，不想都带上blog标签

### ISSUE THREAD

**Issue by happmaoo** [kirito41dd/obsidian-hugo-publish#1]

**Comment by happmaoo** [comment]
或者临时改代码的哪个地方？

**Comment by kirito41dd** [comment]
可以改这里，我有空可以加一下，如果设置里tag留空就sync所有
https://github.com/kirito41dd/obsidian-hugo-publish/blob/master/src/util.ts#L16

**Comment by kirito41dd** [comment]
@happmaoo 1.0.6 支持了，升级就行
