### ISSUE TITLE
Wrong path for images?

### ISSUE THREAD

**Issue by apotenza92** [kirito41dd/obsidian-hugo-publish#11]
Hi, I'm trying to use this plugin to generate a site with some basic linked images. Images appear correctly in Obsidian and show up in the static folder of my hugo root if I leave the static setting empty.

However, when I actually generate the hugo site and get an index.html for that file the html renders correctly in my code editor under 127.0.0.1/public/title but if I go to the actual server started by hugo that uses my base URL from hugo.toml the images do not appear, and just show up as a blank square image icon.

I have been reading the hugo documentation and have seen [this page](https://gohugo.io/content-management/organization), it seems that image paths are now meant to be relative to the content folder instead?

Also look [here](https://gohugo.io/getting-started/directory-structure/#static) where it states:
"Before the introduction of [page bundles](https://gohugo.io/getting-started/glossary/#page-bundle) and [asset pipelines](https://gohugo.io/hugo-pipes/introduction/), the static directory was also used for images, CSS, and JavaScript."

Based on what I've read I think this plugin should be using [Leaf Bundles](https://gohugo.io/content-management/page-bundles/#leaf-bundles) ? Where each Obsidian post becomes it's own index.md file and associated linked files get placed in the same folder.

I'm new to Hugo though so feel free to correct me.

**Comment by kirito41dd** [comment]
Sorry, this doesn't seem to be a plugin issue.
Here is my blog tree.
![图片](https://github.com/user-attachments/assets/19e3c6d2-b03d-45b0-a880-6ddf450db123)
