### ISSUE TITLE
The _index.md file gets deleted

### ISSUE THREAD

**Issue by kdsp-net** [kirito41dd/obsidian-hugo-publish#2]
I think that most people have their blogs in Hugo set up with _index.md to define the list. It should be an option to leave the _index.md file(s) intact.

**Comment by kirito41dd** [comment]
Can you show me some examples to help me understand better?

**Comment by kdsp-net** [comment]
Typically in Hugo when you have a blog it is in folder called "blog" for example. In this folder you would have a file `_index.md` that would define how the "list" layout (eg. the /blog) page - as opposed to the actual blog post that would get the "single" layout. So therefore it would be great if you would not delete the existing `_index.md` file already present in the output folder. It is a reserved filename in Hugo. The typical Hugo structure looks like this:

my-site/            
    └── content/
    │   ├── blog/
    │   │   │   ├── _index.md
    │   │   │   ├── post-1.md
    │   │   │   └── post-2.md
    │   │   └── _index.md
    │   ├── themes/
    │   │   └── my-theme/
    │   └── hugo.toml
    └── etc.

**Comment by kirito41dd** [comment]
Ok, I see

**Comment by kirito41dd** [comment]
@kdsp-net 1.0.6 Published
