### ISSUE TITLE
add option to not delete any file when syncing

### ISSUE THREAD

**Issue by fredleger** [kirito41dd/obsidian-hugo-publish#3]
Having to define patterns to avoid deleting files seems a tedious task. How about letting the user specify which one **shoudl be deleted** (so reversing the option) ?

**Comment by kirito41dd** [comment]
You can use js regex described in this tag
https://github.com/kirito41dd/obsidian-hugo-publish/releases/tag/1.0.6

**Comment by fredleger** [comment]
yes but listing all patterns to ignore is tedious when you just want the sync to keep evrything ...
IMHO the reverse logic is more suitable (list what you allow to be deleted). At least in my use case

**Comment by kirito41dd** [comment]
use `.*` to match all
