### ISSUE TITLE
Tag的处理

### ISSUE THREAD

**Issue by Sunyin0818** [kirito41dd/obsidian-hugo-publish#5]
+ 过程
我给ob中的文档添加了publish标签，调用hugo sync后，生成的hugo页面中也存在了publish标签。
![image](https://github.com/user-attachments/assets/8a171466-059a-418b-a65a-cced1f34550a)

这将会导致hugo渲染的时候，所有的博客必有一个publish标签。
![image](https://github.com/user-attachments/assets/33e8fc4e-0653-47d9-9418-f4257be60831)

我理解的插件中的这个`blog tag`配置，是为了ob中区分文章是否发布，目前的效果感觉比较怪异冗余。

+ 建议
生成hugo时，`blog tag`不加入到font header的tag中
或者作者有其他使用的姿势，还望不吝赐教。

**Comment by kirito41dd** [comment]
可以，下版本给它下掉

**Comment by kirito41dd** [comment]
还是做个开关吧，万一有人用的tag就是想出现在博客里也有可能

**Comment by kirito41dd** [comment]
@deuts Maybe the next two weekends.
