### ISSUE TITLE
FEATURE REQUEST:  Additional setting to limit subdirectory scope of Obsidian notes searched for blog tag

### ISSUE THREAD

**Issue by fseesink** [kirito41dd/obsidian-hugo-publish#8]
Breaking this out as a separate ticket to keep things simple.

As a feature request, would love to see one extra setting to limit the scope that the plugin searches for Obsidian notes.  That is, currently this plugin searches an entire Obsidian vault for any/all pages containing the `blog tag` set in the settings.  However, this means you cannot, for example, leverage Obsidian templates where you want to preset all the frontmatter/etc. for a blog post.

For example, one might have the following directory structure in their Obsidian vault:
<img width="177" alt="image" src="https://github.com/user-attachments/assets/a003ad31-2612-4e2a-8c92-24ccd11d3fbf">

where
- `blog/info.md` is a blog post that references `static/shocked.jpg` in the content of the page
- `Templates/Blog Post.md` is an Obsidian template that contains something like
```
---
title: "{{Title}}"
description: 
date: "{{date:YYYY-MM-DD}}T{{time:HH:mm:ss}}+00:00"
draft: true
tags:
  - blog
---
CONTENT HERE
```
where the idea is that when someone wants to write a new blog post, they create a new page, apply the template to the page, then start writing content.

As it stands, the plugin will go through this vault, see this template file, which has the `blog tag` in it, and see it as a blog post file.

If the plugin would allow for setting the base directory under which the plugin searched, it would be possible to configure the setting to only look in `blog/` for pages with the `blog tag`, thereby preventing the template files from being included in the output.

OR somehow offering a way to EXCLUDE portions of the Obsidian vault so that one can specify not to look in the Templates folder for example.  This might be a bit like the `blog dir keep list`, which I'm still not quite sure how that one works.  But possibly setting a list of RegExs that determine what should be excluded from being searched for the `blog tag` setting.

(Side note:  Because of all this, I actually went looking into TypeScript, though I simply haven't had time to learn it well enough yet, or I'd send a PR.  One day...  But still, got me curious enough to go looking into it.)

**Comment by kirito41dd** [comment]
https://github.com/kirito41dd/obsidian-hugo-publish/releases/tag/1.0.8
